services:
  notion-movie-metadata-updater:
    image: ghcr.io/ehcaning/notion-movie-metadata-updater:latest
    container_name: notion-movie-metadata-updater
    env_file:
      - .env
    ports:
      - "8000:${METRICS_HTTP_PORT:-8000}"
    volumes:
      - ./json_data:/app/json_data
    restart: unless-stopped
